domain_name: cartpole
task_name: swingup
encoder_type: pixel
action_repeat: 8
pre_transform_image_size: 84
image_size: 84
agent: curl_sac
frame_stack: 3
critic_lr: 0.001
actor_lr: 0.001
eval_freq: 10000
batch_size: 128
num_train_steps: 500000
---
domain_name: cheetah
task_name: run
encoder_type: pixel
action_repeat: 4
pre_transform_image_size: 84
image_size: 84
agent: curl_sac
frame_stack: 3
critic_lr: 0.001
actor_lr: 0.001
eval_freq: 10000
batch_size: 128
num_train_steps: 500000
---
domain_name: ball_in_cup
task_name: catch
encoder_type: pixel
action_repeat: 4
pre_transform_image_size: 84
image_size: 84
agent: curl_sac
frame_stack: 3
critic_lr: 0.001
actor_lr: 0.001
eval_freq: 10000
batch_size: 128
num_train_steps: 500000

---

domain_name: reacher
task_name: easy
encoder_type: pixel
action_repeat: 4
pre_transform_image_size: 84
image_size: 84
agent: curl_sac
frame_stack: 3
critic_lr: 0.001
actor_lr: 0.001
eval_freq: 10000
batch_size: 128
num_train_steps: 500000
---
domain_name: walker
task_name: walk
encoder_type: pixel
action_repeat: 2
pre_transform_image_size: 84
image_size: 84
agent: curl_sac
frame_stack: 3
critic_lr: 0.001
actor_lr: 0.001
eval_freq: 10000
batch_size: 128
num_train_steps: 500000

---
domain_name: finger
task_name: spin
encoder_type: pixel
action_repeat: 2
pre_transform_image_size: 84
image_size: 84
agent: curl_sac
frame_stack: 3
critic_lr: 0.001
actor_lr: 0.001
eval_freq: 10000
batch_size: 128
num_train_steps: 500000