name: drq
channels:
  - defaults
dependencies:
  - python=3.7
  - pytorch
  - cudatoolkit=9.2
  - absl-py
  - pyparsing
  - jupyterlab
  - scikit-image
  - pip:
    - gym[atari]
    - opencv-python
    - termcolor
    - tb-nightly
    - imageio
    - imageio-ffmpeg
    - hydra-core
    - pandas
    - ipdb
    - tqdm
    - torchvision
    - yapf
    - mujoco_py
    - sklearn
    - matplotlib
    - kornia
